### ISSUE TITLE
Please Conform it is 'xn' or 'x_cn'

### ISSUE THREAD

**Issue by zelokuo** [kiharalab/ACC-UNet#2]
Hey, dear,
  I am totally interested in your incredible work. however, when I read your code from 522-525 lines in 'ACC_UNet.py', I was confused. In my opinion, it should be 'x_cn = self.sqen(x_cn)' rather not 'xn = self.sqen(xn)'. Am I right, if not, could you please spare a little time to explain the reason?  Thank you very much.

**Comment by nibtehaz** [comment]
Thank you for pointing this out, this was an accidental typo when cleaning the code.
