### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by SwimmingLiu** [kiharalab/ACC-UNet#3]
Hello, may you please provide a link to download all datasets. Thank you very very very much!!!!

**Comment by nibtehaz** [comment]
Hi, you can download the datasets from the following links

https://challenge.isic-archive.com/data/#2018
https://polyp.grand-challenge.org/CVCClinicDB/
https://medicalsegmentation.com/covid19/
https://scholar.cu.edu.eg/?q=afahmy/pages/dataset
https://warwick.ac.uk/fac/cross_fac/tia/data/glascontest/

**Comment by SwimmingLiu** [comment]
Thanks for your link. But is there prosessed datasets?

**Comment by nibtehaz** [comment]
We have not performed any preprocessing.

**Comment by SwimmingLiu** [comment]
Sorry, I saw the code in Load_Dataset.py , and it means that I need make dataset like 
```
train_folder
  --img
     --xxx.png
  --labelcol
     --xxx.png
val_folder
  --...
test_folder
  --...
```
But the datasets I downloaded are nii format. May you share the dataset processed like above format. Because I cannot to slice these nii files to png/jpg format similar with you

**Comment by nibtehaz** [comment]
Hi, yes the dataset directory should be like this.

Sorry, I don't have the processed data with me right now, we completed the experiments one year ago. Even if we had that, I am not sure about the different dataset license policies regarding redistribution. But you can just download the data from the original sources and use for your experiments.

For nii format data, I used the `nibabel` library. For example,

```
import nibabel
import cv2
import numpy as np

imgs = nibabel.load('/home/kihara/nibtehaz/MedicalImageDataset/Covid/tr_im.nii').get_fdata()
msks = nibabel.load('/home/kihara/nibtehaz/MedicalImageDataset/Covid/tr_mask.nii').get_fdata()

img = imgs[:,:,0]
img = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
img = cv2.resize(img, (224,224), interpolation = cv2.INTER_CUBIC)
img = (img-np.min(img))/(np.max(img)-np.min(img))

msk = msks[:,:,0]
msk = cv2.rotate(msk, cv2.ROTATE_90_CLOCKWISE)
msk = cv2.resize(msk, (224,224), interpolation = cv2.INTER_CUBIC)
msk = (msk>0.5)*1.0
```

**Comment by SwimmingLiu** [comment]
Thanks very much!!!!!!
